language: java
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
    - secure: VuYEtooK3gR8Pl1uaa7voTw7DJJ+dptYN2i4fujXQnf+Mg8rMJ1kPtbtCgH1gDpCVPZN1Yeg5LR6yvENWgtyI5ypNHx6Bzl5Q4DjNnBbxQGAeAEjAr3wURBRzHrhwumhv4o2RfR0bwsQaIJ/yp16kJt9PMcoUpAIfPmLeKPj2Sb6HL+J7jN5NSwYPhOcMgoiaSZomtsuuTKin10CwXfAsjNRDY9/mBYHOo8508MyWIvKgTu4sna34X7BJzrfZVu0scjPtDD1odl3eoEZszOTeyTv0LNtMSXG2ypqcfqrDzbwJRvuH4ukyP9yEm9KxlfjjPDY3TniKScNZjPL1W5FWuV3yRjoT2VKF411aibX0N7wPEBfCVBCqzd1brRs36qEYpaZeqqWI7PWDevW6r7JQHds629LZQ+hBkhjMA1sD7nBJ7y2I5oU3xM8xZYgUMQrgoERCJZTCsv03tH5I19y+8+JKTeJgyWCom07OKnm5ZpluWdzKy3cXM9b67+/GD7fAA6odr20PFO0+9r/3RcZSQKltu0Adx3JLqyd39uUKB3XWwDuIceNpFkPz7ph/lROzWyjuUScD/y/+UQONHI8aQCUzdYfjZE49LKvzcytXt0aSx8mbIJkdGqicYsIKXQNziH11C3zb88chRa4dSEJMfV5hGUwzLFozDcHeMIfZjY=
    - secure: BUGMgHulTW798MLJiXOwc9eR/+MYL21/FjwRVlQGkyh+wDWVwHU+jQ6Ma1IiBzUFynmiv/tgqQkxYuvEBAjwCB3eL9eJjq0e3Ve6FVWVJfWcpnFE53i2XafxIbuIRZGXFMU2NTDglFZ8hZzKA+EQivfAU52jbyHMymfjVaWMrfuYhy23Htw2GPly0uVr5KzpIWBIHW4jj5XBrNVsreDNcvgnT4pShZRNyYXX8MMNN0wfc06cqcxgYgwIONLqQo2H8VFPGyvX6UUicKw7gjlaZV6/l6AZs58Crl1tVtc2RGOTRQRb7c0ukluTfXNKRbZ7DMMPZ8fDsWJD+J3g+1kJvxDdrD8NWjSOBMQQc1coHfrR3+yHzUeoNT3p6a1fC/TaN9U2qAnXkT/aBMGysWMWzE2ldvt+PfvqD0FEO0jo9MNj8XaYWvFBkS+6+EKD5C7k2s1rit0TYYnVe1lBNIBZQqC6Ov7SpUG7vaHgqHIbnTirRKj058jnflh2S+eqhs0EwAS+boYnQfO3Ck5CviMAB90z5lGQKLwOUXe4Y2CT7y4PpFfdwAtdrWLNaptqiVfj9XJOmqV6V2Xik1fWDCoanjiCb5381GflfOJJ23153Wv1LhgIAsRb0PWYVdv6mmNe8SbZzAoPRCQI1rDB/Z8JCRm5Tq1BI9CdTaVC8HW6erM=
