language: java
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
    - secure: T28z2gWEUX4iSAJ3KvwHW2HKVADN1L+5E0nAvpngNVuGLMbo1n0aQgAJXKbsTDPxwN7TS0zR2MyRzvO8sX3ZuXiVmAzzmmFn5iH8IjM7FiWvKSc9N0788LWJj4BTWoU+mpb6khFoQe9qgTs5B1Qs/rj4XHQxKeNf0/6La0QSSjTzJKB95Fqb8ENxxaKwVhkaGJcBHC9kpN7Odfz00SzPekqIC5pi7sfjrC09ntVM7swIkT8E7IUgivGtrPhmcOVFY2lyYcHGQeJ3RTm4AArE1+KoBJsZGKJRVX0djjO0ZwPzL5OpWUJFPV4/Fj4KRa/KTyyHTlQcH2nja3JjBolUt8nAHlNcoXBaA2fHg/7AfV8koVGRj7NiEgduUryQsdqQVUCJw7zO1IX6lBAdP/5NmFkTz92XtLDhD/IUA7X8qdTZIKLc6Anoc0ZfBD7vjAe2isRyGA1Y8s6PGX+fcnYAFeVmVVEGiOkbNRgwFq8SgebRBDzasFgOSDh1H9OM8whC/llLITiiRiPqupllzD9A5nEjjQyJ62vzZRUAlSYAsHQ3zJBxjmeZKpX+OA1nQb1+zOMVzOlbMEQ5oMKyWpH/+nSDWhLcXRauolnb8u4hxcqDEEv7aDi6GKFkgvNS+QBK2Abw4Xof0GJjivgJ4lKZVIVEiLYtQMBoguo/IW6b2KE=
    - secure: tEPTifxiAxYJO1Plbzn+Rt2urHvqmfcAjNEp6j/PNhmFHkMubtaVaVAdakkClJ97jf7rp6zn2Lyc1ITLVqpeGz5iIyzdsA4ywT7P3suR5w5ANSb5SGVFcuMMLWSHZ7JBGNDKFhcPjdv7T4OcuwoDmLpLMo/CvyUVzeMHMHDjrrrVRUyJGuvwnYiNK5VPqpqRFC6hlF2YxznpKPS/6jd3x4j8PvOj3I9A9dCULUYe5ssHZ+GxHf1mKCtvENEvZl4ThKqvOh74KWc8FUJh2rPaoCNQoSCwhqJl4W2e0btR24cdaKyV5nPTUpVJ7vzHSVoWEPgTPxdDFdMkBkOFoN/M99F7rxzs9olM9eA1h6iorLxiPkYUZs6HBDWvL1x0rOQYjP52W4tmqE9hcA4fGsQuoZRKZ3B3sOwnr16DVWsD3A7oXHs+SlZ1ktiqYlNdmgUf/gYWDBugaJEdWThp4mY9oZUIpE5RDG2uvY8IpuWx6AZhXTZ241vCFX/ZeAGGBXdNCpusfg3DUNpfvg2EaE03mbndbOrr8dhVU6+SqAilgUm9gyyBfAy3qE3KpEttKGHfH+VaPrX8qVjvDi/ATyxPfk6uOfx2w5VqKT9fI2E/OQZ4nEqXGmC0S5Ic2AmFq+lW52Gt0AGo8+OxRPT68hoHrYkXTdfilcFLnHpBqSjgPa0=
